{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "39ce4de6_24a49fa8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1143
      },
      "writtenOn": "2025-10-04T11:53:34Z",
      "side": 1,
      "message": "@adrien.beraud@savoirfairelinux.com was there some actual failure in the CI, or is this good to go?",
      "revId": "47f06f44252976e3ab1bddee9c29672cd8cbe9ac",
      "serverId": "1e26b4c1-6b8c-47ff-9df7-501b633d3b5a"
    }
  ]
}