{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2662074a_209f041b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 610
      },
      "writtenOn": "2022-01-05T09:50:20Z",
      "side": 1,
      "message": "If it works for you, I agree to merge. But since the same tests failed on two Arch Linux computers, the problem can raise in the future.\n\nWhat cppunit version are you using?",
      "revId": "7130c6df954b0faa7d46443b10b215e9bb55cb89",
      "serverId": "1e26b4c1-6b8c-47ff-9df7-501b633d3b5a"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e84a5447_a571a44e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 220
      },
      "writtenOn": "2022-01-05T17:15:51Z",
      "side": 1,
      "message": "1.15.1\n\nBut start will fail if there is another daemon started. We call it only if (not Manager::instance().initialized). Not sure how the constructor can be called twice, this doesn\u0027t really make sense to me.\n\nSo not sure what\u0027s wrong with your setup. But anyway, this is not a build issue, your patch is fine for building and starting the tests. Fixing he fail can be in another aprt if necessary",
      "parentUuid": "2662074a_209f041b",
      "revId": "7130c6df954b0faa7d46443b10b215e9bb55cb89",
      "serverId": "1e26b4c1-6b8c-47ff-9df7-501b633d3b5a"
    }
  ]
}